### ISSUE TITLE
스킬 트리 큰 느낌

### ISSUE THREAD

**Issue by majecty** [SNUGDC/DeepDarkDungeon#10]
김고수와 박초보가 있다고 가정했습니다.

김고수 : 블러드본, 타이탄 소울, 뉴클리어 쓰론 등의 게임의 엔딩을 본 사람
박초보 : 게임은 이것 저것 해봤지만 액션 게임은 별로 해본적이 없음.

### 스킬트리의 구성

* 플레이 스타일에 따라서 스킬트리를 3~5개
* 한 스킬트리당 10개의 스킬이 있음
  * 5번째, 10번째 스킬은 강력한 스킬
  * 나머지 스킬들은 수치를 조금씩 올려주는 스킬

#### 쉬운 난이도로 만들 때

* 김고수가 5시간정도 플레이했을 때 한 트리의 모든 스킬을 찍을 수 있다.
* 박초보가 5시간정도 했을 때 한 트리의 절반정도의 스킬을 찍을 수 있다.
* 김고수가 전체 챕터의 절반정도 갔을 때 한 트리의 모든 스킬을 찍을 수 있다.

#### 어려운 난이도로 만들 때

* 김고수가 게임을 끝낼때쯤 겨우겨우 스킬트리를 전부 찍을 수 있다.
  * 좋은 스킬을 찍어서 안정적으로 가야할 때는 일종의 노가다가 필요하다.
* 박초보는 10시간정도 플레이 했을 때 5번째 좋은 스킬을 찍을 수 있다.

**Comment by majecty** [comment]
피드백 있으면 알려주세요.
난이도도 쉬운 난이도와 어려운 난이도 중에서도 고민중입니다. 의견 있으시면 절 도와주세요.

**Comment by yulcat** [comment]
스킬트리를 제공한다는 것은 한 트리 안에서도 어떤 스킬을 찍을 것인지 고민하고 선택하는 재미를 부여하는 것인데, 한 트리의 모든 스킬을 찍는 걸 기준으로 삼는 건 이상하지 않을까요?
효율성으로 따졌을 때, 극단적으로 한가지 스타일만 파는 유저가 아니고서야 한 트리의 최종스킬을 찍으면 그 트리의 나머지 스킬들을 찍는 게 아니라, 다른 트리를 파기 시작하도록 유도하는 게 맞는 것 같습니다.

난이도는 쉬운 난이도 쪽이 더 합리적인 난이도로 보이네요. 다만 초보 유저도 플레이타임 대비 스킬트리 진행율은 고수 유저와 대등하길 원합니다. 고수 유저는 어차피 스킬트리를 똑같이 찍어도 더 효율적인 골드 배분으로 훨씬 많은 구간을 진행할 수 있을테고, 스킬트리를 많이 찍어서 이득을 보려는 쪽은 초보 유저니까요. 다만 어떻게 짜야 2~3층 안에서 자주 죽는 유저와 안죽고 쭉쭉 진행하는 유저가 비슷한 시간대비 스킬포인트를 얻을 수 있을지는 연구가 필요할 것 같습니다.

**Comment by renios** [comment]
- 첫 층에서 죽으면서 스킬포인트를 모으는 어뷰징을 막는 방법이라는 부분에서 생각나서 몇자 적어봅니다.
- 일단 첫째로는 해당 구간의 몬스터 리젠 횟수를 제한하는 방법이 있습니다. 다크소울 2에서는 (소울 시리즈에서는 유일하게) 동일한 몬스터를 20회 정도 잡으면 더이상 리젠이 되지 않습니다. 다만 소울 시리즈는 죽을때 소울을 모두 잃기 때문에 초보 유저의 노가다를 막아버리는 부작용이 있었지만, 여기서는 아니죠. (제가 이해하기로는 로비로 돌아와야 스킬을 찍을 수 있는 것으로 아는데 죽었을때 소울이 전부 날아간다면 스킬을 찍을수가 없...) 
몬스터가 아예 나오지 않는 것이 이상하다면 일정 횟수 이상 도전할 경우 골드만 주고 소울은 주지 않는 방식으로 적용할 수도 있을 것 같습니다.
- 또는 소울의 종류를 세분화하여, 상급 스킬을 올리기 위해서는 뒤쪽 스테이지에서 나오는 상급 소울이 필요한 방식으로 만들 수도 있겠지만 이 방법은 진행도와 스킬 습득도가 비례하기 때문에 '나는 컨이 안되니까 일주일쯤 노가다하더라도 적정렙보다 짱짱 높여서 갈거야!' 라는 진행이 불가능해집니다. 위에서 이야기한 '비슷한 시간대비 비슷한 스킬포인트 습득'과는 다소 대치되는 부분입니다.
아, 상급 스킬은 아니더라도 하급 스킬을 잔뜩 찍어서 진행할 수는 있겠네요. 그러면 고수 유저가 1~5티어 스킬을 하나씩 찍으면서 돌파해나가는 시간에 초보 유저는 1티어 3개, 2티어 2개 이런 식으로 찍을 수는 있겠습니다.

- 아니면 다른 방법이 있을까요?
- 만약 소울의 종류를 세분화한다면, 하급 > 상급 환전은 불가능해도 (되면 구분한 의미가 없으니) 상급 > 하급 환전은 가능했으면 좋겠습니다. 고수 유저가 두번째 스킬트리를 찍기 위해 다시 1층에서 노가다하는 건 그닥 내키는 경험은 아닐테니까요.

**Comment by majecty** [comment]
@yulcat 
1. 간단한 일직선의 스킬트리를 생각하고 있었어요. 그래서 마지막 스킬을 찍게 되면 모든 스킬이 다 찍히는 스킬트리인거죠.

2. 상점에서 소울을 팔아서 살 수 있는 특별한 일회용 아이템이 있는 건 어떨까요?

**Comment by majecty** [comment]
지난 일요일에 정수형이랑 이야기하면서 스킬 트리에 대해 구두로 한 번 정리했습니다.
자세한 내용은 곧 정리해서 올릴게요.

이 이슈는 닫습니다.
