### ISSUE TITLE
보스 디자인 초안

### ISSUE THREAD

**Issue by renios** [SNUGDC/DeepDarkDungeon#20]
작은 용암 웅덩이에 유저 키의 약 3~4배 정도로 큰 칠흑의 대검이 꽂혀있다가, 조금 후 대검을 중심으로 화면 위쪽 반이 바닥째로 폭발하면서 바닥 타일들이 흩날린다.
이후 상반신만 나온 거대한 불의 거인과 전투 시작.

보스 - 불의 지배자 수르트

- 피격 범위 : 손(근접 / 원거리), 몸통(원거리)
- 넉백 : 없음
- 경직 : 없음
- 속성 : 불
- 특이 패시브 : 불 속성 공격 무효화

- 화염 폭풍(세로) : 화면을 가로로 3등분해서, 위 - 중간 - 아래에 화염 폭풍이 몰아친다. 1~2초정도 해당 영역이 붉게 변함 -> 1~2초 화염 폭풍 & 다음 영역이 붉게 변함 -> ...
시간 간격은 해당 영역의 중앙에 서있던 플레이어라면 화면이 붉어지자마자 탈출하면 약간 여유있고, 위쪽이 붉어지는데 맨 위에 있다면 아무리 칼타이밍으로 반응해도 맞게 된다.
기술을 피하거나 공격할 때도 되도록이면 너무 가장자리에 있지 않도록 의식하는 것이 중요.

- 화염 폭풍(가로) : 화면을 세로로 3등분해서 좌-중-우 또는 우-중-좌 순서로 화염 폭풍이 몰아친다. 메커니즘은 세로형과 동일.

- 내려치기 : 유저가 한 위치에 오래 있으면 (3초 이상?) 회색 -> 검은 그림자가 생기고 (1초정도) 그 위치로 ‘강하게’ 주먹을 내리친다. 맞은 유닛은 매우 큰 데미지를 받고 장시간 스턴에 걸린다. 3~5초 정도 후에 다시 손을 올리는데, 그동안 손을 타겟으로 한 근접 공격이 가능하다. 
내려치기가 시전된 영역은 이후 용암 웅덩이로 변한다. 따라서 전투가 진행될수록 유저들이 쓸 수 있는 영역은 계속 좁아진다.
용암 웅덩이에서는 사나운 불씨가 일정 시간마다 나온다.

- 마구치기 : 보스의 체력이 일정 퍼센트 깎일 때 마다 사용. 보스가 화난 표정을 지으면서 주먹으로 화면 여기저기를 난타한다. 0.5초정도 회색 그림자가 생기고 0.5초정도 주먹이 떨어졌다가 다른 곳을 치기를 약 7-10회정도 반복.
마지막은 양 손을 들어 화면 랜덤한 두 위치에 '내려치기'를 쓴다.
보스가 화난 표정을 지으면 공격을 멈추고 방 여기저기를 뛰어다니면서 피하다가, 내려치기가 시전되는 것을 보고 공격을 한 후 다시 산개한다.

- 붕괴 : 한 쪽 팔에 최대체력의 50%를 넘는 데미지가 누적되면 팔이 파괴된다. 보스가 일시적으로 공격을 멈추고, 붕괴될 팔이 3초정도 점점 밝은 빛을 내다가 터지며 주변에 광역 데미지와 넉백을 가한다.

- 화염 보호막 : 일정 주기로 (약 10초 당 5초 정도?) 보스가 자기 본체 주변에 화염 보호막을 친다. 이 때 원거리 공격을 날리면 화염 보호막이 점점 밝게 빛나다가 일정 데미지 이상을 받으면 터지면서 전체 유닛에게 화염 데미지와 넉백을 가한다. 
혼자 플레이하면 보호막 시간이 다 되기 전에 터질 일은 거의 없겠지만, 파티플레이 시에는 보호막의 상태를 보면서 적절한 원거리 딜 조절이 필요.

**Comment by renios** [comment]
- 가로 화염폭풍의 예시 : https://youtu.be/0YG2KKvLcLc?t=10m54s (불의 땅 - 라그나로스)
10:57쯤부터 중간 -> 바깥 -> 안쪽 순으로 폭발합니다.
- 내려치기를 쓸때마다 유저들이 사용할 수 있는 공간이 작아지는 기믹은 이스 1 최종보스전에서 따온 기믹입니다.
영상 : https://www.youtube.com/watch?v=rywKRtV_9Bc
다만 영상에서 바닥이 사라지는 조건은 '보스가 피격당했을 때' 로, 위의 기획과는 트리거가 다릅니다.

**Comment by yulcat** [comment]
거의 장판기 위주의 보스라 직접 보스와 싸운다는 느낌이 잘 안 드는 것 같아요.

![gr1](https://cloud.githubusercontent.com/assets/6895426/13064962/f4c495aa-d49a-11e5-81bf-34d0d43d9445.jpg)

이 친구처럼 상반신만 튀어나온 녀석이 보스룸을 양손으로 기어다니면서 직접 싸우는 건 어떨까요?

**Comment by renios** [comment]
<보스 전투 플로우>

변경점 : 몸통에도 딜을 할 수 있다. 다만 손에는 두 배의 데미지가 들어가고, 자꾸 몸통 근처에만 있으면 내려치기를 몇 번 맞으면 자리가 없어지므로 몸통만 닥딜하는 택틱은 불가능(데미지가 엄청 쎄면 되겠지만).

< 1페이즈 : 체력 100%~80% >
기본 택틱 : 내려치기를 유도한 후 옆으로 살짝 피하고, 손이 찍히면 손을 때린다.
손에는 몸통보다 2배의 데미지가 들어간다.

+ 가끔 보스의 눈이 빛나면서 양쪽 주먹에 불이 생기는 경우가 있는데, 이 때는 내려치기가 타격지점 주변에도 화염데미지를 주므로 좀 멀리 빠져야 한다. 1~2페이즈 때는 약 20% 정도 확률로, 3페이즈에는 약 40% 정도 확률로 시전한다.

+ 다인 플레이시는, 랜덤한 사람에게 주먹이 떨어지므로 너무 산개해 있으면 다른 유저들이 딜을 넣기가 힘들어짐. 그리고 주먹이 떨어졌을 때 효과적으로 딜을 넣지 못하면 움직일 수 없는 영역(용암 웅덩이)이 점점 넓어지므로 트롤이 된다.

< 2페이즈 : 체력 80%~30% >

보스의 체력이 80%가 화염 폭풍을 쓴다. 화염 폭풍을 쓰는 동안은 내려치기를 쓰지 않는다.

내려치기 4번 -> 마구치기 -> 내려치기 4번 -> ...의 패턴으로 공격한다.

체력 50%가 되면 화염 폭풍을 한 번 더 쓴다. 화염 폭풍이 끝나면 화염 보호막을 시전한다. 이 보호막은 원거리 공격으로 가한 데미지가 일정 이상 누적되면 폭발하거나, 10초가 지나거나, 3페이즈가 시작되면 사라진다.

< 3페이즈 : 체력 30%~0% >

보스의 체력이 30%가 되면, 강화된 화염 폭풍을 쓴다. 화염 폭풍을 쓰는 동안은 내려치기나 마구치기를 쓰지 않는다.
일반 화염폭풍은 3등분 중 '안전지대 2 + 위험지대 1' 이지만 강화된 화염 폭풍은 '안전지대 1 + 위험지대 2' 의 구성으로 되어있다. 

내려치기 3번 -> 마구치기 -> 내려치기 3번 -> ...의 패턴으로 공격하며, 불이 감긴 내려치기의 빈도가 높아진다.

체력 20%가 되면 화염 보호막을 시전한다. 이 보호막은 해제되지 않는다.

체력 10%가 되면 강화된 화염 폭풍을 한 번 더 쓴다.

**Comment by renios** [comment]
일단 보스를 구현하기는 무리이므로 닫겠습니다

**Comment by majecty** [comment]
닫아놓으면 다시 잘 안볼 거 같은데 위키에 적어놓는 건 어떤가요!
