### ISSUE TITLE
던전 생성기 요구사항 결정

### ISSUE THREAD

**Issue by yulcat** [SNUGDC/DeepDarkDungeon#4]
던전 생성기는 방 프리팹들을 이어붙여 하나의 던전 층을 만든다. 이 던전 생성기에서 한 층의 던전을 만들려면 주어진 방들은 특정한 조건을 만족시켜야 한다. 이 방들에 요구되는 조건을 미리 결정하여야 기획자들은 그 조건에 맞춰 방을 디자인하고, 던전 생성기가 그 방들을 이어서 한 층의 던전을 완성할 수 있다.

**Comment by yulcat** [comment]
모든 방은 i*j개의 단위 사각형으로 이루어진 직사각형 안에 정확하게 들어맞아야 한다.

**Comment by noisum** [comment]
일단 동작이 되는 초안이 만들어졌으니 현재 구조 상 어쩔 수 없는 문제점을 적어두겠습니다.

1. 기본 전제가 방은 직사각형이라는 가정을 깔고 있어서, 방 모양이 적어도 두 모서리는 방 경계 직사각형과 맞닿아야 합니다. 즉, ㄱ자형 방이나 모래시계 모양 방은 어떻게 되지만 원형 방은 불가능합니다.
2. 사실 직사각형 외의 방을 상상조차 못 하고 있었기 때문에(...) 현재 출입구 트리거는 방 경계 직사각형 위에 있어야 합니다. 즉, 출입구 트리거(JointMarker)는 방의 가장 바깥쪽 모서리에만 놓을 수 있으며(생각해보니 출입구라면 당연한 것 같기도 하고?) 그 모서리는 x축 혹은 y축에 평행해야 합니다.
3. 방의 회전은 고려조차 하지 않았습니다. 즉, 다이아몬드 형태의 방은 출입구가 존재할 수가 없어서 안됩니다(...). 그리고 이 부분에서 생기는 문제인데, 현재 알고리즘은 그냥 방끼리 이어주기만 하고 있으므로 그 층에 있는 방들이 모두 출입구의 방향이 동일하다면 끼워맞추는게 불가능해져서 던전 생성이 반드시 실패합니다.

**Comment by yulcat** [comment]
반드시 두 모서리가 경계 직사각형과 맞닿아야 하나요? JointMarker만 방 경계 직사각형 위에 놓일 수 있다면 +형 방도 만들 수 있는 게 아니었나...?
방의 회전은 고려하지 않은 게 맞음. 시점 때문에라도 방은 회전시키지 말고 만들 때 의도된 방향으로 배치되어야 합니다. 다만 회전된 모양의 방을 따로 만들어서-(room1_0, room1_90, room1_180, room1_270)-서로 같은 방 코드네임을 갖도록 해서 중복되지 않게 만드는 방안은 가능할 듯. (room1_90이 이미 존재한다면 room1_270은 배치되지 않음)

**Comment by noisum** [comment]
아 맞습니다. jointmarker만 모서리에 있으면 되는 상황이긴 합니다.

**Comment by noisum** [comment]
현재 결정 사항을 위키에 적어두었습니다.
